# Example Playbook
- name: Compute Engine Instance Examples
  hosts: localhost
  tasks:
    - name: delete test-instances
      # Basic termination of instance.
      gce:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        instance_names: "{{ vms | join(',') }}"
        zone: australia-southeast1-b
        state: absent
      tags:
        - delete
      register: gce

    - name: remove config settings
      blockinfile:
        dest: "{{ config }}"
        marker: "# {mark} {{ item }} ansible"
        state: absent
      with_items:
        - "{{ vms }}"

    - name: display config settings
      debug:
        msg: "# {{ item }} ansible"
      with_items:
        - "{{ vms }}"

