version: '3'
services:
  jenkins:
    build: .
    privileged: true
    user: "jenkins"
    ports:
      - 80:8080
      - 50000:50000
    container_name: sshdjenkins
    environment:
      - JENKINS_USER="jenkins"
      - JENKINS_PASSWORD="foobar"
    volumes:
      - /opt/jenkins:/var/lib/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /etc/sysconfig/docker:/etc/sysconfig/docker
