---
- hosts: vm
  become: yes
  vars:
    jenkins_home: /var/lib/jenkins
    jenkins_local: /opt/jenkins
    image: servianjenkins
    password: foobar
    sock: /var/run/docker.sock
    docker: /usr/bin/docker
    sysconfig: /etc/sysconfig/docker
    uid: 1000
    port: 80
    sport: 8080
    log: /tmp/foo.log
  tasks:
    - name: Create jenkins directory beforehand
      file: path={{ jenkins_local }} state=directory owner={{uid}} mode=0755

    - name: Build a local jenkins docker container
      shell: |
        [ -d {{jenkins_local}} ] || { mkdir {{jenkins_local}}; } 
        [ -d {{docker}} ] && { rm -rf {{docker}}; touch {{docker}}; } 
        docker build -t {{image}} /tmp/works/. > {{log}}
        echo "DONE!" >> {{log}}
      args:
        warn: no

    # port 9191 needs to be opened by cloud server tools beforehand
    - name: insert firewalld rule
      firewalld: port={{port}}/tcp permanent=true state=enabled immediate=yes

    - name: Run jenkins docker as daemon
      shell: |
        docker run --restart=always -u {{uid}} -e JENKINS_PASSWORD={{password}} -p {{port}}:{{sport}} -p 50000:50000 -v {{sock}}:{{sock}}:z -v {{docker}}:{{docker}} -v {{sysconfig}}:{{sysconfig}}:z -v {{jenkins_local}}:{{jenkins_home}}:z  -d {{image}}
      args:
        warn: no
